### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by boada** [fred3m/astromatic_wrapper#4]
It looks like `disutils` has continued to evolve. So if you try to install with pip you get:

 `    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6djjsbtl/astromatic-wrapper/setup.py", line 25, in <module>
        conf = config.ConfigParser()
    AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
`
It appears they have renamed `ConfigParser` to `RawConfigParser`

cheers.

One possible solution to this is pull request #3.

**Comment by simontorres** [comment]
Any news on this issue? I'm having a similar problem. Is this project to be archived or something?

**Comment by boada** [comment]
@simontorres it has almost certainly just be abandoned by the author. Best bet is gonna be a fork and to fix it yourself.

**Comment by simontorres** [comment]
It looks that way, thanks!

**Comment by navarete** [comment]
Well, I just faced the same problem.
The solution was to modify line 24 of setup.py from `conf = config.ConfigParser()` to 
`conf = config.RawConfigParser()`, then install it from the source!
